### ISSUE TITLE
Error: Cannot find module './properties'

### ISSUE THREAD

**Issue by snatesan** [chad3814/CSSStyleDeclaration#39]
This issue, https://github.com/chad3814/CSSStyleDeclaration/issues/20, occurring again with version cssstyle@0.2.32.

 Cannot find module './properties'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/cssstyle/lib/CSSStyleDeclaration.js:230:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by tteltrab** [comment]
Fixed in 0.2.33:
https://github.com/chad3814/CSSStyleDeclaration/commit/7ee6e5ed5e478eeaf0174660629fd6edab91b2fd#commitcomment-15916839

**Comment by snatesan** [comment]
Can you please remove 0.2.32 from NPM? I have this module as nested
dependency and somehow it is retrieving 0.2.32 version.

**Comment by domenic** [comment]
It won't help if he removes it; it's still in your local cache. You need to clear your npm cache.
